default: all

css:
    ./static/build-css.sh

wasm:
    ./frontend/build.sh

wasm-prod:
    ./frontend/build.sh -Oz

all: css wasm

prod: css wasm-prod

run: all
    node serve.mjs

# Debug builds are auto-signed by gradle and can be installed directly with adb.
android-debug: all
    ./mobile/build.sh debug

# Release builds require mobile/android/keystore.properties to be set up.
# See mobile/android/keystore.properties.example for the required fields.
android-release: prod
    ./mobile/build.sh release

clean:
    # cabal build artifacts
    rm -rf frontend/dist-newstyle
    # assembled web app (wasm + bundled js + html + css)
    rm -rf frontend/dist
    # compiled css
    rm -rf static/out
    # gradle build output (apk + intermediates)
    rm -rf mobile/android/build
    # files generated by cap sync android
    rm -rf mobile/android/capacitor-cordova-android-plugins
    rm -f mobile/android/capacitor.settings.gradle
    rm -rf mobile/android/app/src/main/assets
    rm -f mobile/android/app/src/main/res/xml/config.xml
