default: css wasm-dev

css:
    ./static/build-css.sh

native-dev: css
    ghcid \
        --command='cabal --project-dir=frontend --enable-multi-repl repl exe:frontend lib:frontend' \
        --test='Main.main'

wasm-dev:
    ./frontend/build.sh

wasm-prod:
    ./frontend/build.sh -Oz

wasm-run: default
    node serve.mjs

# Debug builds are auto-signed by gradle and can be installed directly with adb.
android-debug: css wasm-dev
    ./mobile/build.sh debug

# Release builds require mobile/android/keystore.properties to be set up.
# See mobile/android/keystore.properties.example for the required fields.
android-release: css wasm-prod
    ./mobile/build.sh release

clean:
    # cabal build artifacts
    rm -rf frontend/dist-newstyle
    # assembled web app (wasm + bundled js + html + css)
    rm -rf frontend/dist
    # compiled css
    rm -rf static/out
    # gradle build output (apk + intermediates)
    rm -rf mobile/android/build
    # files generated by cap sync android
    rm -rf mobile/android/capacitor-cordova-android-plugins
    rm -f mobile/android/capacitor.settings.gradle
    rm -rf mobile/android/app/src/main/assets
    rm -f mobile/android/app/src/main/res/xml/config.xml
