default: all

css:
    cd static && ./build-css.sh

wasm:
    cd frontend && ./build.sh

wasm-prod:
    cd frontend && ./build.sh -Oz

all: css wasm

prod: css wasm-prod

run: all
    node serve.mjs

android: all
    cd mobile && ./build.sh

clean:
    # cabal build artifacts
    rm -rf dist-newstyle
    # assembled web app (wasm + bundled js + html + css)
    rm -rf frontend/dist
    # compiled css
    rm -rf static/out
    # gradle build output (apk + intermediates)
    rm -rf mobile/android/build
    # files generated by cap sync android
    rm -rf mobile/android/capacitor-cordova-android-plugins
    rm -f mobile/android/capacitor.settings.gradle
    rm -rf mobile/android/app/src/main/assets
    rm -f mobile/android/app/src/main/res/xml/config.xml
